viewer:
  image: camptocamp/puppet-catalog-diff-viewer:0.2.5
  labels:
    io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=$${stack_name}/generator
  environment:
    S3_BUCKET: ${S3_BUCKET}
    S3_ACCESS_KEY: ${VIEWER_S3_ACCESS_KEY}
    S3_SECRET_KEY: ${VIEWER_S3_SECRET_KEY}
  volumes:
  - puppetcatalogdiff:/data:ro

generator:
  image: camptocamp/puppet-catalog-diff:1.6.0-11
  environment:
    S3_BUCKET: ${S3_BUCKET}
    S3_DIR: ${S3_DIR}
    MASTER1: ${CATALOG_DIFF_MASTER_1}
    MASTER2: ${CATALOG_DIFF_MASTER_2}
    THREADS: 3
    USE_PUPPETDB: 'yes'
    AWS_ACCESS_KEY_ID: ${CATALOG_DIFF_S3_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${CATALOG_DIFF_S3_SECRET_KEY}
    JOB_NAME1: 'catalog_diff_report'
    JOB_COMMAND1: ${JOB_COMMAND1}
    JOB_TIME1: ${JOB_TIME1}
    SYNC: ${SYNC}
  external_links:
  - ${PUPPETDB_SERVICE}:puppetdb
  - ${PUPPETSERVER_SERVICE}:puppet
  - ${PUPPETCA_SERVICE}:puppetca
  volumes:
  - puppetcatalogdiff:/data
  - puppetcatalogdiffssl:/etc/puppetlabs/puppet/ssl
