viewer:
  image: camptocamp/puppet-catalog-diff-viewer
  environment:
    S3_BUCKET: ${S3_BUCKET}
    S3_ACCESS_KEY: ${VIEWER_S3_ACCESS_KEY}
    S3_SECRET_KEY: ${VIEWER_S3_SECRET_KEY}

generator:
  image: camptocamp/puppet-catalog-diff:1.6.0-2
  environment:
    SITE: ${CATALOG_DIFF_SITE}
    MASTER1: ${CATALOG_DIFF_MASTER_1}
    MASTER2: ${CATALOG_DIFF_MASTER_2}
    THREADS: 3
    USE_PUPPETDB: 'yes'
    S3_ACCESS_KEY: ${CATALOG_DIFF_S3_ACCESS_KEY}
    S3_SECRET_KEY: ${CATALOG_DIFF_S3_SECRET_KEY}
    CRON_SCRIPT: ${CRON_SCRIPT}
  external_links:
  - ${PUPPETDB_SERVICE}:puppetdb
  - ${PUPPETSERVER_SERVICE}:puppet
  - ${PUPPETCA_SERVICE}:puppetca
